version: '3.7'

services:
  couchbase:
    image: couchbase:enterprise-7.1.1
    container_name: feathers-couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    volumes:
      - couchbase_var:/opt/couchbase/var
      - ./scripts:/scripts
    restart: unless-stopped

volumes:
    couchbase_var: